config/routes.rb
Zoeetrope::Application.routes.draw do
  resource :session do
    post :create
    get :destroy
  end

  root 'home#index'
  get 'home/index'
  get 'contact', to: 'contact#index'

  resources :projects do
    resources :used_technologies, only: %w[index create destroy]
    put 'used_technologies/sort', controller: :used_technologies, as: :sort_technologies
  end

  resources :screenshots, only: %w[index create edit update destroy]

  get 'sitemap.xml' => 'home#sitemap', format: :xml, as: :sitemap
  get 'robots.txt' => 'home#robots', format: :text, as: :robots
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  authenticates_with_sorcery!
  validates :email, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :title, presence: true
  validates :intro, presence: true

  has_many :used_technologies, -> { order('sort_order') }
  has_many :technologies, through: :used_technologies
  has_many :screenshots, -> { order('sort_order') }

  scope :live, -> { where(draft: false).order('sort_order DESC') }
end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
  before_create :default_sort_order

  mount_uploader :image, ScreenshotUploader
  belongs_to :project

  private

  def default_sort_order
    self.sort_order = project.screenshots.count + 1
  end
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true

  has_many :used_technologies
  has_many :projects, through: :used_technologies
end

app/models/used_technology.rb
class UsedTechnology < ActiveRecord::Base
  before_create :default_sort_order

  belongs_to :project
  belongs_to :technology

  private

  def default_sort_order
    self.sort_order = project.used_technologies.count + 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def robots
    render 'home/robots.txt.erb', layout: false, content_type: 'text/plain'
  end

  def sitemap
    path = Rails.root.join('public', 'sitemaps', 'sitemap.xml')

    if File.exists?(path)
      render xml: open(path).read
    else
      render text: 'Sitemap not found.', status: :not_found
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login, except: [:index, :show]

  def index
    @featured_projects = Project.live.where(featured: true)
    @projects = Project.live.where(featured: false)
    @drafts = Project.where(draft: true)
  end

  def show
    @project = Project.find(params[:id])

    if @project.draft && !logged_in?
      redirect_to projects_path
    end
  end

  # Admin only

  def new
    @project = Project.new
  end

  def create
    project = Project.create project_params
    redirect_to project_path(project)
  end

  def edit
    @project = Project.find(params[:id])
    @screenshot = Screenshot.new
  end

  def update
    project = Project.find(params[:id])
    project.update_attributes project_params
    redirect_to project_path(project)
  end

  private

  def project_params
    params.require(:project).permit(:title, :intro, :description, :license, :repository, :download_url, :featured, :draft, :sort_order)
  end
end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController

  before_filter :require_login

  def create
    screenshot = Screenshot.new screenshot_params

    if screenshot.save
      redirect_to edit_project_path(screenshot.project)
    else
      render json: screenshot.errors
    end
  end

  def edit
    @screenshot = Screenshot.find(params[:id])
    @project = @screenshot.project
  end

  def update
    screenshot = Screenshot.find(params[:id])
    screenshot.update_attributes screenshot_params
    redirect_to edit_project_path(screenshot.project)
  end

  def destroy
    screenshot = Screenshot.find(params[:id])
    project = screenshot.project
    screenshot.destroy
    redirect_to edit_project_path(project)
  end

  private

  def screenshot_params
    params.require(:screenshot).permit(:image, :caption, :sort_order, :project_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_url if logged_in?
  end

  def create
    user = login(params[:email], params[:password])
    redirect_to projects_url
  end

  def destroy
    logout if logged_in?
    redirect_to root_url
  end
end

app/controllers/used_technologies_controller.rb
class UsedTechnologiesController < ApplicationController

  before_filter :find_project

  def index
    @used_technologies = @project.used_technologies
  end

  def create
    technology = Technology.find_or_create_by(title: params[:title])
    @used_technology = @project.used_technologies.new(technology: technology)

    unless @used_technology.save
      render json: used_technology.errors, :status => 422
    end
  end

  def sort
    params[:order].each_with_index do |id, order|
      used_technology = @project.used_technologies.find(id)
      used_technology.update_attributes(sort_order: order)
    end

    render json: { success: true }
  end

  def destroy
    @project.used_technologies.where(id: params[:id]).first.destroy

    render json: { success: true }
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end
end

app/views/contact/index.html.erb
<div class="jumbotron">
    <h1><%= t '.title' %></h1>
    <p class="lead"><%= t '.lead' %></p>
</div>

<div class="contact-container">
    <div class="contact-item">
        <h3><%= t '.email' %></h3>
        <%= mail_to 'zoee.silcock@gmail.com', 'zoee.silcock_at_gmail.com' %>
    </div>
    <div class="contact-item">
        <h3><%= t '.twitter' %></h3>
        <%= link_to '@zoees', 'https://twitter.com/zoees' %>
    </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
    <h1><%= t '.title' %></h1>
    <p class="lead"><%= t '.lead' %></p>
</div>

<div class="row">
    <div class="col-sm-9">
        <p><%= t '.about_me1' %></p>
        <p><%= raw t '.about_me2' %></p>
        <p><%= t '.about_me3' %></p>
    </div>
    <div class="col-sm-3 photo">
        <%= image_tag 'zoee.jpg', data: { path: image_path('zoee.jpg'), silly_path: image_path('zoee_silly.jpg')} %>
    </div>
</div>

<h2><%= t '.favorite_resources' %></h2>
<dl>
    <dt><%= link_to 'Reddit', 'http://reddit.com/', target: '_blank' %></dt>
    <dd>As with most tools it's about how you use it. Used correctly it can be a tremendous resource.</dd>
    <dt><%= link_to 'Unity Answers', 'http://answers.unity3d.com/', target: '_blank' %></dt>
    <dd>If you ever have a question about Unity you'll find the answer here.</dd>
    <dt><%= link_to 'Unity List', 'http://unitylist.com/', target: '_blank' %></dt>
    <dd>Good resource for finding open source projects related to Unity 3D.</dd>
    <dt><%= link_to 'raywenderlich.com', 'http://www.raywenderlich.com/', target: '_blank' %></dt>
    <dd>A gold mine of information on iOS and game programming.</dd>
    <dt><%= link_to 'StackOverflow', 'http://stackoverflow.com/', target: '_blank' %></dt>
    <dd>Goes without saying but it has helped me countless times. Although I usually get there via Google.</dd>
    <dt><%= link_to 'RailsGuides', 'http://guides.rubyonrails.org/', target: '_blank' %></dt>
    <dd>The best place to learn Rails. Part reference, part best practices, all quality.</dd>
    <dt><%= link_to 'Mozilla Developer Network', 'https://developer.mozilla.org', target: '_blank' %></dt>
    <dd>This is the most reliable source for information on JavaScript and CSS IMHO.</dd>
    <dt><%= link_to 'Dive into HTML5', 'http://diveintohtml5.info/', target: '_blank' %></dt>
    <dd>Old news, but still nice to have all the information presented well in one place.</dd>
    <dt><%= link_to 'Learn Vimscript the Hard Way', 'http://learnvimscriptthehardway.stevelosh.com/', target: '_blank' %></dt>
    <dd>The most complete resource I have found on Vimscript.</dd>
</dl>

app/views/home/robots.txt.erb
Sitemap: <%= sitemap_url %>

app/views/layouts/_google_tag_manager.html.erb
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-NTTSQK" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NTTSQK');</script>
<!-- End Google Tag Manager -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>zoeetrope.com</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
  <%= render partial: 'layouts/google_tag_manager' if Rails.env.production? %>

  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header pull-left">
        <%= link_to 'zoeetrope.com', root_path, class: 'navbar-brand' %>
      </div>
      <%= render :partial => 'shared/navbar' %>
    </div>
  </div>

  <div class="container">
      <%= yield %>
  </div>

  <footer></footer>
</body>
</html>

app/views/projects/_edit_screenshots.html.erb
<h4><%= t '.screenshots' %></h4>

<ol class="screenshots edit">
<% @project.screenshots.each do |screenshot| %>
    <li>
        <p><strong><%= screenshot.caption %></strong></p>
        <%= image_tag screenshot.image.thumb.url %>
        <p>
            <%= link_to t('.edit'), edit_screenshot_path(screenshot), class: 'btn btn-xs btn-default' %>
            <%= link_to t('.remove'), screenshot_path(screenshot), method: :delete, class: 'btn btn-xs btn-default', data: { confirm: t('.remove_confirmation') } %>
        </p>
    </li>
<% end %>
</ol>

<h4><%= t '.new_screenshot' %></h4>
<%= render partial: 'screenshots/form' %>

app/views/projects/_feature.html.erb
<div class="col-md-6 featured-project">
    <h4><%= link_to feature.title, project_path(feature) %></h4>
    <p><%= simple_format feature.intro %></p>
    <%= link_to t('.more-details'), project_path(feature), class: 'btn btn-success btn-sm' %>
    <% if logged_in? %>
        <%= link_to edit_project_path(feature), class: 'btn btn-default btn-sm' do %>
            <%= t '.edit' %>
            <i class="fa fa-pencil"></i>
        <% end %>
    <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_for @project, html: { role: 'form' } do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :intro %>
        <%= f.text_area :intro, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: 10 %>
    </div>

    <div class="form-group">
        <%= f.label :license %>
        <%= f.text_field :license, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :repository %>
        <%= f.text_field :repository, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :download_url %>
        <%= f.text_field :download_url, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :sort_order %>
        <%= f.text_field :sort_order, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :featured %>
        <%= f.check_box :featured, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :draft %>
        <%= f.check_box :draft, class: 'form-control' %>
    </div>

    <%= f.submit t('.submit'), class: 'btn btn-default' %>
<% end %>

app/views/projects/_form_grid.html.erb
<div class="row">
    <div class="col-sm-8">
        <%= render partial: 'form' %>
    </div>
    <div class="col-sm-4">
        <%= render partial: 'technologies_form' %>
        <%= render partial: 'edit_screenshots' %>
    </div>
</div>

app/views/projects/_project.html.erb
<li>
    <%= link_to project.title, project_path(project) %>
    <% if logged_in? %>
        <%= link_to edit_project_path(project), class: 'btn btn-xs btn-default' do %>
            <%= t '.edit' %>
            <i class="fa fa-pencil"></i>
        <% end %>
    <% end %>
</li>

app/views/projects/_technologies_form.html.erb
<h4><%= t '.technologies' %></h4>
<div class="technologies-form" data-project-id="<%= @project.id %>"></div>

app/views/projects/edit.html.erb
<%= render :partial => 'form_grid' %>

app/views/projects/index.html.erb
<div class="jumbotron">
    <h1><%= t '.title' %></h1>
    <p class="lead"><%= t '.lead_html' %></p>
    <%= link_to 'https://github.com/zoeesilcock', class: 'btn btn-success btn-lg', target: '_blank' do %>
        <%= t '.github-link' %>
        <i class="fa fa-chevron-right"></i>
    <% end %>
    <%= link_to 'https://connect.unity.com/u/5816193c32b30600171becf2', class: 'btn btn-success btn-lg', target: '_blank' do %>
        <%= t '.unity-connect-link' %>
        <i class="fa fa-chevron-right"></i>
    <% end %>
    <% if logged_in? %>
        <%= link_to new_project_path, class: 'btn btn-default btn-lg' do %>
            <%= t '.new-project' %>
            <i class="fa fa-plus"></i>
        <% end %>
    <% end %>
</div>

<% @featured_projects.each_slice(2) do |row| %>
    <div class="row">
        <%= render partial: 'feature', collection: row %>
    </div>
<% end %>

<h3><%= t '.more_projects' %></h3>
<ol class="more-projects">
    <%= render partial: 'project', collection: @projects %>
</ol>

<% if logged_in? %>
    <h3><%= t '.drafts' %></h3>
    <ol class="more-projects">
        <%= render partial: 'project', collection: @drafts %>
    </ol>
<% end %>

app/views/projects/new.html.erb
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<div class="jumbotron">
    <h1><%= @project.title %></h1>
    <p><%= simple_format @project.intro %></p>
    <p>
	<span class="pull-right"><%= @project.license %></span>
	<% unless @project.repository.blank? %>
	    <%= link_to @project.repository, class: 'btn btn-success', target: '_blank' do %>
		<%= t('.repository') %>
		<i class="fa fa-chevron-right"></i>
	    <% end %>
	<% end %>
	<% unless @project.download_url.blank? %>
	    <%= link_to @project.download_url, class: 'btn btn-success', target: '_blank' do %>
		<%= t('.download') %>
		<i class="fa fa-chevron-right"></i>
	    <% end %>
	<% end %>
	<% if logged_in? %>
	    <%= link_to edit_project_path(@project), class: 'btn btn-default' do %>
		<%= t '.edit' %>
		<i class="fa fa-pencil"></i>
	    <% end %>
	<% end %>
    </p>
    <% if @project.used_technologies.size > 0 %>
	<div>
	    <% @project.used_technologies.each do |ut| %>
		<span class="label label-primary"><%= ut.technology.title %></span>
	    <% end %>
	</div>
    <% end %>
</div>

<% if @project.screenshots.size > 0 %>
    <ol class="screenshots">
	<% @project.screenshots.each do |screenshot| %>
	    <li>
		<%= link_to screenshot.image.url, data: { lightbox: 'screenshots', title: screenshot.caption } do %>
		    <%= image_tag screenshot.image.thumb.url, data: { toggle: 'modal', target: '#screenshot-modal', image: screenshot.image.url, caption: screenshot.caption } %>
		<% end %>
		<p class="caption"><%= screenshot.caption %></p>
	    </li>
	<% end %>
    </ol>
<% end %>

<div class="row">
    <div class="col-xs-12">
	<%= simple_format @project.description %>
    </div>
</div>

app/views/screenshots/_form.html.erb
<%= form_for @screenshot, html: { role: 'form' } do |f| %>
    <div class="form-group">
        <%= f.label :caption %>
        <%= f.text_field :caption, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :weight %>
        <%= f.text_field :sort_order, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.file_field :image %>
    </div>

    <%= f.hidden_field :project_id, value: @project.id %>

    <%= f.submit t('.submit'), class: 'btn btn-default' %>
<% end %>

app/views/screenshots/edit.html.erb
<%= image_tag @screenshot.image.url %>
<%= render partial: 'form' %>

app/views/shared/_navbar.html.erb
<ul class="nav navbar-nav pull-right">
    <%= content_tag :li, :class => controller?('home') ? 'active' : '' do %>
	<%= link_to root_path do %>
	    <i class="fa fa-home"></i>
	    <span class="title"><%= t('.home') %></span>
	<% end %>
    <% end %>
    <%= content_tag :li, :class => controller?('projects') ? 'active' : '' do %>
	<%= link_to projects_path do %>
	    <i class="fa fa-file-code-o"></i>
	    <span class="title"><%= t('.projects') %></span>
	<% end %>
    <% end %>
    <%= content_tag :li, :class => controller?('contact') ? 'active' : '' do %>
	<%= link_to contact_path do %>
	    <i class="fa fa-phone"></i>
	    <span class="title"><%= t('.contact') %></span>
	<% end %>
    <% end %>
</ul>